<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="SampleService" targetNamespace="http://SampleService" xmlns:bons1="http://www.employee.details" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://SampleService" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="SampleServiceHttpBinding" originalBindingStyle="document"/>
        <generatedXSD location="SampleService_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <wsdl:types>
    
        <xsd:schema targetNamespace="http://SampleService" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
            <xsd:import namespace="http://www.employee.details" schemaLocation="EmpInfo.xsd"/>
            <xsd:include schemaLocation="SampleService_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="getEmployeeDetailsRequestMsg">
    <wsdl:part element="tns:getEmployeeDetails" name="getEmployeeDetailsParameters"/>
  </wsdl:message>
  <wsdl:message name="getEmployeeDetailsResponseMsg">
    <wsdl:part element="tns:getEmployeeDetailsResponse" name="getEmployeeDetailsResult"/>
  </wsdl:message>
  <wsdl:portType name="SampleService">
    <wsdl:operation name="getEmployeeDetails">
      <wsdl:input message="tns:getEmployeeDetailsRequestMsg" name="getEmployeeDetailsRequest"/>
      <wsdl:output message="tns:getEmployeeDetailsResponseMsg" name="getEmployeeDetailsResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SampleServiceHttpBinding" type="tns:SampleService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getEmployeeDetails">
      <soap:operation soapAction="http://SampleService/getEmployeeDetails"/>
      <wsdl:input name="getEmployeeDetailsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getEmployeeDetailsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="SampleServiceHttpService">
    <wsdl:port binding="tns:SampleServiceHttpBinding" name="SampleServiceHttpPort">
      <soap:address location="http://localhost:7804/SampleService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>